server:
  port: 9000

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:dcbapp-dev
    driverClassName: org.h2.Driver
    password: psw123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect